name: hello_world
author: valory
version: 0.1.0
description: A simple demonstration of a simple ABCI application
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiapubcoersqnsnh3acia5hd7otzt7kjxekr6gkbrlumv6tkajl6jm
fingerprint_ignore_patterns: []
agent: valory/hello_world:0.1.0:bafybeiho6mkcg2agaaqicwp6ze2pnmoclzp44dyvdqqs5srhd2xkjjmwpi
number_of_agents: 1
deployment: {}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    gnosis:
      address: ${GNOSIS_LEDGER_RPC:str:http://localhost:8545}
      chain_id: ${GNOSIS_CHAIN_ID:int:100}
      poa_chain: ${IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
