agent_name: langchain_basic
author: nrosavalory
version: 0.1.0
license: Apache-2.0
description: Langchain agent example.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeicatvo4dqfunaspsdm3qru5gsfyfubjar7rbo2yos4zxtm5rstr4u
  __init__.py: bafybeial6x3dxput7zsfux7vnfjjscde63iurldki6ufbuiogedwucuzte
fingerprint_ignore_patterns: []
connections: []
contracts: []
protocols: []
skills: []
customs:
- nrosavalory/agent:0.1.0:bafybeicfatevxp2yoj32qs6wnwzzeclrapt33k2upulxjpy22uqd5axtom
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config: {}
dependencies: {}
default_connection: null
