agent_name: hello_world
author: valory
version: 0.1.0
license: Apache-2.0
description: Hello World ABCI example.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeifzdekpjcas6egpwxj24tir5ozzffmkq5ecyi6rw3i6fqfd763etu
  __init__.py: bafybeiehvk4wlv2bcbplwc66owg4qdnisiihijq7iegcmjjxtz3dulnrgm  
fingerprint_ignore_patterns: []
connections: []
contracts: []
protocols: []
skills: []
customs: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config: {}
dependencies: {}
default_connection: null
