name: langchain_basic
author: nrosavalory
version: 0.1.0
description: A simple demonstration of an langchain agent application
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeifa3tgy23zmlrdobrw4og36pl7dny2zeiprxu5lwtjbvsl55fakqq
fingerprint_ignore_patterns: []
agent: nrosavalory/langchain_basic:0.1.0:bafybeiebet5bp7g5jzy7qzb6cz7ji2vc6sl4dqgwfitb22ub4xumgpvqny
number_of_agents: 1
deployment: {}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    gnosis:
      address: ${GNOSIS_LEDGER_RPC:str:http://localhost:8545}
      chain_id: ${GNOSIS_CHAIN_ID:int:100}
      poa_chain: ${IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
